network:
  version: 2
  ethernets:
    eth0:
      dhcp6: false
      addresses:
      - 172.19.0.80/24
      gateway4: 172.19.0.1
      nameservers:
        addresses: 
        - 172.19.0.1
        search: []
      routes:
      - to: default
        via: 172.19.0.1
    net0:
      dhcp4: false
      dhcp6: true
      gateway4: 172.19.0.1
      nameservers:
        addresses: 
        - 172.19.0.1
        search: []
      routes:
      - to: default
        via: 172.19.0.1
